use_frameworks!

platform :ios, '8.0'

target 'SGFFmpegFramework_Example' do
  pod 'SGFFmpegFramework', :path => '../'

  target 'SGFFmpegFramework_Tests' do
    inherit! :search_paths

    
  end
end
